
import { PlanRequest, Question, TimetableConstraints, Subject, Difficulty, WeeklySchedule, DailySchedule } from "../types";
import { MOCK_QUESTION_DB } from "../constants";

// Helper to simulate "processing" time for a realistic feel
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Offline Study Plan Generator
 * Creates a deterministic plan based on inputs without AI.
 */
export const generateStudyPlan = async (request: PlanRequest): Promise<string> => {
  await delay(800); // Simulate "Thinking"
  const { topics, daysAvailable, hoursPerDay, focusArea } = request;

  let planMarkdown = `## 📅 ${daysAvailable}-Day Action Plan\n`;
  planMarkdown += `**Focus:** ${focusArea} | **Daily Commitment:** ${hoursPerDay} Hours\n\n`;
  planMarkdown += `This plan is designed to optimize your preparation for JEE using spaced repetition and active recall.\n`;
  planMarkdown += `---\n\n`;

  const topicsList = [...topics];
  let topicIndex = 0;

  for (let day = 1; day <= daysAvailable; day++) {
    planMarkdown += `### Day ${day}\n`;
    
    // Assign topics cyclically
    const topicsForToday = [];
    if (topicsList.length > 0) {
      // Pick 1 primary topic
      topicsForToday.push(topicsList[topicIndex]);
      topicIndex = (topicIndex + 1) % topicsList.length;
    }
    
    const primaryTopic = topicsForToday[0] || "Revision of backlog";
    const slotDuration = Math.floor(hoursPerDay / 2);

    if (focusArea === "Theory Intensive") {
        planMarkdown += `- **Session 1 (${slotDuration}h):** 📖 **Theory Deep Dive** - ${primaryTopic}. Read NCERT and class notes. Focus on derivations.\n`;
        planMarkdown += `- **Session 2 (${hoursPerDay - slotDuration}h):** ✍️ **Short Notes** - Create formula sheets for ${primaryTopic} and solve basic illustrations.\n`;
    } else if (focusArea === "Problem Solving") {
        planMarkdown += `- **Session 1 (${slotDuration}h):** 🧩 **Guided Practice** - Solve 20-30 Mains level questions on ${primaryTopic}.\n`;
        planMarkdown += `- **Session 2 (${hoursPerDay - slotDuration}h):** 🚀 **Challenge Mode** - Attempt 10 Advanced level problems or PYQs for ${primaryTopic}.\n`;
    } else if (focusArea === "Revision & Mock Tests") {
        planMarkdown += `- **Session 1:** 📝 **Topic Test** - Take a timed test on ${primaryTopic}.\n`;
        planMarkdown += `- **Session 2:** 🔍 **Analysis** - Analyze errors and revise weak concepts.\n`;
    } else {
        // Balanced
        planMarkdown += `- **Session 1 (${slotDuration}h):** 📖 **Concept Review** - Quick theory recap of ${primaryTopic}.\n`;
        planMarkdown += `- **Session 2 (${hoursPerDay - slotDuration}h):** ✏️ **Problem Practice** - Solve Exercise 1 & 2 for ${primaryTopic}.\n`;
    }
    
    planMarkdown += `\n`;
  }
  
  planMarkdown += `\n---\n*Generated by BT PrepTracker Smart Engine*`;
  return planMarkdown;
};

/**
 * Offline Question Generator
 * Fetches from a local DB or generates templated questions.
 */
export const generatePracticeQuestions = async (topicName: string, difficulty: string, subject?: Subject): Promise<Question[]> => {
  await delay(600);
  
  // Robust subject detection
  let derivedSubject = subject;
  if (!derivedSubject) {
      if (['Kinematics', 'Newton', 'Work', 'Rotation', 'Gravitation', 'Electrostatics', 'Current', 'Optics', 'Units'].some(k => topicName.includes(k))) derivedSubject = Subject.PHYSICS;
      else if (['Mole', 'Atomic', 'Bonding', 'Gaseous', 'Equilibrium', 'Organic', 'GOC', 'Isomerism', 'Block'].some(k => topicName.includes(k))) derivedSubject = Subject.CHEMISTRY;
      else derivedSubject = Subject.MATHS;
  }

  const dbQuestions = (derivedSubject ? MOCK_QUESTION_DB[derivedSubject] : []) || [];
  
  // Return mixed real + templated questions to ensure we always have 5
  const results: Question[] = [];

  // 1. Add real questions from DB if available
  dbQuestions.forEach(q => {
     if (q.questionText && q.options && q.correctAnswer && q.explanation) {
       results.push({
         ...q as Question,
         difficulty: difficulty // Override for display consistency
       });
     }
  });

  // 2. Fill remaining with templated questions
  while (results.length < 5) {
    const num = results.length + 1;
    results.push({
      questionText: `[${topicName}] Conceptual Question #${num}: Which of the following statements is true regarding this topic at a ${difficulty.split(' ')[0]} level?`,
      options: [
        `Option A: Statement regarding concept 1 of ${topicName}`,
        `Option B: Statement regarding concept 2 of ${topicName}`,
        `Option C: Statement regarding concept 3 of ${topicName}`,
        `Option D: Statement regarding concept 4 of ${topicName}`
      ],
      correctAnswer: `Option A: Statement regarding concept 1 of ${topicName}`,
      explanation: `**Analysis:**\nThis is a generated practice question. In a real exam scenario, you would analyze the specific conditions given. Since the difficulty is **${difficulty}**, ensure you check for edge cases in ${topicName}.`,
      difficulty: difficulty
    });
  }

  return results.slice(0, 5);
}

/**
 * Offline Timetable Generator
 * Returns a structured object instead of raw markdown for better rendering control.
 */
export const generateWeeklyTimetable = async (constraints: TimetableConstraints): Promise<WeeklySchedule> => {
  await delay(500);
  const { coachingDays, coachingTime, schoolDetails, sleepSchedule } = constraints;
  
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const schedule: DailySchedule[] = [];

  days.forEach(day => {
    const isCoaching = coachingDays.includes(day);
    const isSchool = schoolDetails.attending && day !== 'Sun';
    const isSunday = day === 'Sun';
    
    let activities: string[] = [];
    let type: DailySchedule['type'] = 'school';
    let studyHours = 0;

    if (isSunday) {
      type = 'exam';
      activities = [
        "09:00 - 12:00: 📝 Full Syllabus / Part Test",
        "14:00 - 16:00: 🔍 Test Analysis (Crucial)",
        "17:00 - 20:00: 🔄 Revision of Weak Areas"
      ];
      studyHours = 6;
    } else {
      // Morning Slot
      if (isSchool) {
        activities.push(`🏫 School (${schoolDetails.start} - ${schoolDetails.end})`);
        type = 'school';
      } else {
        activities.push(`🏠 Morning Study (08:00 - 13:00): Problem Solving (Maths/Physics)`);
        studyHours += 5;
        type = 'holiday'; // No school
      }

      // Afternoon/Evening Slot
      if (isCoaching) {
         type = 'coaching';
         activities.push(`🏢 Coaching (${coachingTime.start} - ${coachingTime.end})`);
         activities.push(`🌙 Night: Revise class notes + 1 hr HW`);
         studyHours += 1;
      } else {
         activities.push(`💪 Evening Study: Deep Work (4 hours) - Alternating Subjects`);
         activities.push(`🌙 Night: Revision + NCERT Reading`);
         studyHours += 4;
      }
    }

    schedule.push({
      day,
      activities,
      type,
      hours: studyHours
    });
  });

  return {
    summary: `Goal: Maximize self-study while balancing Coaching & School.`,
    schedule,
    guidelines: [
      `Sleep: Ensure you sleep from ${sleepSchedule.bed} to ${sleepSchedule.wake}. Consistency is key.`,
      `Breaks: Take 10 min breaks every 50 mins of study.`,
      `Coaching Days: Focus on revising what was taught same-day.`,
      `Non-Coaching Days: These are your goldmines. Aim for 8+ hours of self-study.`
    ]
  };
};
