
import { PlanRequest, Question, TimetableConstraints, Subject, Difficulty, WeeklySchedule, DailySchedule } from "../types";
import { MOCK_QUESTION_DB } from "../constants";

// Helper to simulate "processing" time for a realistic feel
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Offline Study Plan Generator
 * Creates a deterministic plan based on inputs without AI.
 */
export const generateStudyPlan = async (request: PlanRequest): Promise<string> => {
  await delay(800); // Simulate "Thinking"
  const { topics, daysAvailable, hoursPerDay, focusArea } = request;

  let planMarkdown = `## 📅 ${daysAvailable}-Day Action Plan\n`;
  planMarkdown += `**Focus:** ${focusArea} | **Daily Commitment:** ${hoursPerDay} Hours\n\n`;
  planMarkdown += `This plan is designed to optimize your preparation for JEE using spaced repetition and active recall.\n`;
  planMarkdown += `---\n\n`;

  const topicsList = [...topics];
  let topicIndex = 0;

  for (let day = 1; day <= daysAvailable; day++) {
    planMarkdown += `### Day ${day}\n`;
    
    // Assign topics cyclically
    const topicsForToday = [];
    if (topicsList.length > 0) {
      // Pick 1 primary topic
      topicsForToday.push(topicsList[topicIndex]);
      topicIndex = (topicIndex + 1) % topicsList.length;
    }
    
    const primaryTopic = topicsForToday[0] || "Revision of backlog";
    const slotDuration = Math.floor(hoursPerDay / 2);

    if (focusArea === "Theory Intensive") {
        planMarkdown += `- **Session 1 (${slotDuration}h):** 📖 **Theory Deep Dive** - ${primaryTopic}. Read NCERT and class notes. Focus on derivations.\n`;
        planMarkdown += `- **Session 2 (${hoursPerDay - slotDuration}h):** ✍️ **Short Notes** - Create formula sheets for ${primaryTopic} and solve basic illustrations.\n`;
    } else if (focusArea === "Problem Solving") {
        planMarkdown += `- **Session 1 (${slotDuration}h):** 🧩 **Guided Practice** - Solve 20-30 Mains level questions on ${primaryTopic}.\n`;
        planMarkdown += `- **Session 2 (${hoursPerDay - slotDuration}h):** 🚀 **Challenge Mode** - Attempt 10 Advanced level problems or PYQs for ${primaryTopic}.\n`;
    } else if (focusArea === "Revision & Mock Tests") {
        planMarkdown += `- **Session 1:** 📝 **Topic Test** - Take a timed test on ${primaryTopic}.\n`;
        planMarkdown += `- **Session 2:** 🔍 **Analysis** - Analyze errors and revise weak concepts.\n`;
    } else {
        // Balanced
        planMarkdown += `- **Session 1 (${slotDuration}h):** 📖 **Concept Review** - Quick theory recap of ${primaryTopic}.\n`;
        planMarkdown += `- **Session 2 (${hoursPerDay - slotDuration}h):** ✏️ **Problem Practice** - Solve Exercise 1 & 2 for ${primaryTopic}.\n`;
    }
    
    planMarkdown += `\n`;
  }
  
  planMarkdown += `\n---\n*Generated by BT PrepTracker Smart Engine*`;
  return planMarkdown;
};

/**
 * Offline Question Generator
 * Fetches from a local DB or generates templated questions.
 */
export const generatePracticeQuestions = async (topicName: string, difficulty: string, subject?: Subject): Promise<Question[]> => {
  await delay(600);
  
  // Robust subject detection
  let derivedSubject = subject;
  if (!derivedSubject) {
      if (['Kinematics', 'Newton', 'Work', 'Rotation', 'Gravitation', 'Electrostatics', 'Current', 'Optics', 'Units'].some(k => topicName.includes(k))) derivedSubject = Subject.PHYSICS;
      else if (['Mole', 'Atomic', 'Bonding', 'Gaseous', 'Equilibrium', 'Organic', 'GOC', 'Isomerism', 'Block'].some(k => topicName.includes(k))) derivedSubject = Subject.CHEMISTRY;
      else derivedSubject = Subject.MATHS;
  }

  const dbQuestions = (derivedSubject ? MOCK_QUESTION_DB[derivedSubject] : []) || [];
  
  // Return mixed real + templated questions to ensure we always have 5
  const results: Question[] = [];

  // 1. Add real questions from DB if available
  dbQuestions.forEach(q => {
     if (q.questionText && q.options && q.correctAnswer && q.explanation) {
       results.push({
         ...q as Question,
         difficulty: difficulty // Override for display consistency
       });
     }
  });

  // 2. Fill remaining with templated questions
  while (results.length < 5) {
    const num = results.length + 1;
    results.push({
      questionText: `[${topicName}] Conceptual Question #${num}: Which of the following statements is true regarding this topic at a ${difficulty.split(' ')[0]} level?`,
      options: [
        `Option A: Statement regarding concept 1 of ${topicName}`,
        `Option B: Statement regarding concept 2 of ${topicName}`,
        `Option C: Statement regarding concept 3 of ${topicName}`,
        `Option D: Statement regarding concept 4 of ${topicName}`
      ],
      correctAnswer: `Option A: Statement regarding concept 1 of ${topicName}`,
      explanation: `**Analysis:**\nThis is a generated practice question. In a real exam scenario, you would analyze the specific conditions given. Since the difficulty is **${difficulty}**, ensure you check for edge cases in ${topicName}.`,
      difficulty: difficulty
    });
  }

  return results.slice(0, 5);
}

/**
 * Offline Timetable Generator
 * Returns a structured object instead of raw markdown for better rendering control.
 */
export const generateWeeklyTimetable = async (constraints: TimetableConstraints): Promise<WeeklySchedule> => {
  await delay(500);
  const { coachingDays, coachingTime, schoolDetails, sleepSchedule } = constraints;
  
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const subjects = ['Physics', 'Maths', 'Chemistry']; // Order of rotation
  let subjectIndex = 0; // Tracks which subject is next for Deep Work

  const schedule: DailySchedule[] = [];

  days.forEach(day => {
    const isCoaching = coachingDays.includes(day);
    const isSchool = schoolDetails.attending && day !== 'Sun';
    const isSunday = day === 'Sun';
    
    let activities: string[] = [];
    let type: DailySchedule['type'] = 'school';
    let studyHours = 0;

    if (isSunday) {
      type = 'exam';
      activities = [
        "08:00 - 09:00: 🧠 Quick Formula Revision",
        "09:00 - 12:00: 📝 Full Syllabus / Part Test (Simulate Exam Hall)",
        "12:00 - 14:00: 🥗 Lunch & Brain Rest",
        "14:00 - 16:00: 🔍 **Critical**: Test Analysis (Identify Silly Mistakes)",
        "16:30 - 19:30: 🔄 Revision of Weak Areas found in Test",
        "20:00 - 21:00: 📅 Plan next week's targets"
      ];
      studyHours = 6;
    } else {
      // --- Morning Slots ---
      if (isSchool) {
        activities.push(`🏫 School (${schoolDetails.start} - ${schoolDetails.end})`);
        type = 'school';
      } else {
        // Dummy School / Holiday
        type = 'holiday';
        const sub1 = subjects[subjectIndex % 3];
        const sub2 = subjects[(subjectIndex + 1) % 3];
        
        activities.push(`🌅 06:30 - 08:30: 🧘‍♂️ Morning Ritual & Inorganic Chemistry (Memorization)`);
        activities.push(`🧠 09:00 - 11:30: 🚀 Deep Work - ${sub1} (Theory + Examples)`);
        activities.push(`☕ 11:30 - 12:00: Break`);
        activities.push(`✏️ 12:00 - 14:30: 🧩 Problem Solving - ${sub2} (Timed Practice)`);
        studyHours += 5; // Morning productivity
      }

      // --- Afternoon Buffer ---
      activities.push(`🔋 14:30 - 16:00: Lunch, Power Nap (20m) & Recharge`);

      // --- Evening / Night Slots ---
      if (isCoaching) {
         type = 'coaching';
         // Before Coaching
         activities.push(`🎒 16:00 - ${coachingTime.start}: Pre-class review (Last lecture notes)`);
         
         // Coaching
         activities.push(`🏢 Coaching (${coachingTime.start} - ${coachingTime.end})`);
         
         // Post Coaching - CRITICAL REVISION
         activities.push(`🍲 Dinner Break (45 mins)`);
         activities.push(`🔄 **Priority**: Revise Today's Class Notes (1.5 hrs)`);
         activities.push(`✍️ Solve 10-15 HW Questions based on today's class (1 hr)`);
         
         studyHours += 2.5; 
      } else {
         // Non-Coaching Evening (Deep Work)
         // Calculate which subject to focus on based on rotation
         let eveningSubject;
         if (isSchool) {
             // If school day, we need to fit 2 subjects in evening
             eveningSubject = `${subjects[subjectIndex % 3]} & ${subjects[(subjectIndex + 1) % 3]}`;
             subjectIndex += 2; // Advance by 2
         } else {
             // If dummy school, we did 2 subjects in morning, do the 3rd one now
             eveningSubject = subjects[(subjectIndex + 2) % 3];
             subjectIndex += 1; // Advance rotation
         }

         activities.push(`🚀 16:30 - 19:00: Deep Work - ${eveningSubject}`);
         activities.push(`☕ 19:00 - 19:30: Evening Walk / Break`);
         activities.push(`📝 19:30 - 21:00: Revision of Backlog / Old Topics`);
         activities.push(`🍲 21:00 - 21:45: Dinner`);
         activities.push(`🌙 21:45 - 22:45: NCERT Reading / Error Log Review`);
         
         studyHours += (isSchool ? 4.5 : 4);
      }
    }

    schedule.push({
      day,
      activities,
      type,
      hours: studyHours
    });
  });

  return {
    summary: `Balanced Routine: Prioritizes immediate revision on coaching days and subject rotation on free days.`,
    schedule,
    guidelines: [
      `Sleep: Strict sleep schedule ${sleepSchedule.bed} to ${sleepSchedule.wake} is non-negotiable for memory consolidation.`,
      `Coaching Days: DO NOT touch new books. Only revise class notes and solve immediate HW.`,
      `Non-Coaching Days: These are for 'Deep Work'. Switch mobile off during 2.5hr slots.`,
      `Breaks: Take 5-10 min active breaks (walk/stretch) every 50 mins. Avoid scrolling.`,
      `Subject Balance: If you studied Physics/Maths heavily today, start with Chemistry tomorrow.`
    ]
  };
};
